# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.dfs3 <- function(x, g, vis1, comp, cont) {
    invisible(.Call(`_MyGraph_dfs3`, x, g, vis1, comp, cont))
}

.find1 <- function(subset, i) {
    .Call(`_MyGraph_find1`, subset, i)
}

.Union <- function(subset, x, y) {
    invisible(.Call(`_MyGraph_Union`, subset, x, y))
}

.boruvka <- function(graph, adj, comp) {
    .Call(`_MyGraph_boruvka`, graph, adj, comp)
}

Boruvka <- function(matrixpeso, adjacencymatrix) {
    .Call(`_MyGraph_Boruvka`, matrixpeso, adjacencymatrix)
}

adjacencyMatrix <- function(input) {
    .Call(`_MyGraph_adjacencyMatrix`, input)
}

BellmanFord <- function(graph, source) {
    .Call(`_MyGraph_BellmanFord`, graph, source)
}

.dfs <- function(x, g, vis1) {
    invisible(.Call(`_MyGraph_dfs`, x, g, vis1))
}

component <- function(m) {
    .Call(`_MyGraph_component`, m)
}

.ricercamin <- function(p, u, n1) {
    .Call(`_MyGraph_ricercamin`, p, u, n1)
}

dijkstra <- function(w, src) {
    .Call(`_MyGraph_dijkstra`, w, src)
}

floydWarshall <- function(graph) {
    .Call(`_MyGraph_floydWarshall`, graph)
}

.find <- function(index, parenti) {
    .Call(`_MyGraph_find`, index, parenti)
}

.union1 <- function(x, y, parenti) {
    .Call(`_MyGraph_union1`, x, y, parenti)
}

.chiamakruskal <- function(weigth, adj, comp) {
    .Call(`_MyGraph_chiamakruskal`, weigth, adj, comp)
}

Kruskal <- function(matrixpeso, adjacencymatrix) {
    .Call(`_MyGraph_Kruskal`, matrixpeso, adjacencymatrix)
}

weight <- function(input, matr) {
    .Call(`_MyGraph_weight`, input, matr)
}

.pagerank <- function(adjacencymatrix, comp, nodes) {
    .Call(`_MyGraph_pagerank`, adjacencymatrix, comp, nodes)
}

.dfs2 <- function(x, g, vis1, cont) {
    invisible(.Call(`_MyGraph_dfs2`, x, g, vis1, cont))
}

.component2 <- function(adjacency, vis) {
    .Call(`_MyGraph_component2`, adjacency, vis)
}

pageRank <- function(adjacencymatrix) {
    .Call(`_MyGraph_pageRank`, adjacencymatrix)
}

.chiamaprim <- function(graph, adj, comp) {
    .Call(`_MyGraph_chiamaprim`, graph, adj, comp)
}

prim <- function(matrixpeso, adjacencymatrix) {
    .Call(`_MyGraph_prim`, matrixpeso, adjacencymatrix)
}

